version: 0.0
os: linux
files:
  - source: /
    destination: /ubuntu/apps/optilyz
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
