version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/valentines-payment/
hooks:
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
